### ISSUE TITLE
Value too large

### ISSUE THREAD

**Issue by fritzdacat** [georgringer/t3monitoring_client#42] opened 2019-02-11 12:14 UTC
I receive the following error message when I want to query the client with the monitoring_client version 9.0.2:

#1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: disk_total_space(): Value too large for defined data type in /mnt/webxxx/a3/xxx/xxxxx/htdocs/www/Typo3v9/master/releases/20190211120621/public/typo3conf/ext/t3monitoring_client/Classes/Provider/ServerInformationProvider.php line 32

**Comment by josefglatz** [comment] 2019-09-14 05:12
@fritzdacat I can't reproduce that. Can you give details about the environment?

**Comment by josefglatz** [comment] 2022-08-30 13:40
ping @fritzdacat

**Comment by fritzdacat** [comment] 2022-08-30 14:09
the customer is no longer on this webspace. since then we no longer have the error message.

**Comment by georgringer** [comment] 2022-09-12 12:39
closing the issue

**Closed by georgringer** 2022-09-12 12:39 UTC
